name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Test with coverage
        run: yarn test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
